### ISSUE TITLE
Correct "Customs clearance detail cannot be null." issue to get intl shipping quote

### ISSUE THREAD

**Issue by njcyx** [scottcwilson/zencart_fedexrest#1]
`if ($order->delivery['country']['iso_code_2'] != "US") {
            $rate_data ["requestedShipment"]["customsClearanceDetail"] = [
                  "commodities" => [
                     [
                     "description" => "Goods",
                     "quantity" => "1",
                     "quantityUnits" => "PCS",
                     "weight" => [
                        "units" => "LB",
                        "value" => ($_SESSION['cart']->show_weight()),
                     ],
                     "customsValue" => [
                        "amount" => ($_SESSION['cart']->show_total()),
                        "currency" => "USD",
                     ],
                  ],
               ],
            ];
         }`

Add this block behind the section of $rate_data, about line 415. "dutiesPayment" section is not necessary to get a quote.

**Comment by njcyx** [comment]
In this section, I use the shopping cart weight and order value in the request data. I'm not sure the value here is "declared value' or "goods value". If "declared value", it may affect the shipping quote if the product is very expensive. But if "goods value", it will not affect the shipping quote. Maybe more tests are needed...

**Comment by scottcwilson** [comment]
This is what makes it tricky.  I can just use the retail value but that's really too high.  I have considered adding a coefficient so you can reduce the value to get to approximate cost, which is what they're expecting.  Still noodling on this.

**Comment by scottcwilson** [comment]
This needed a few tweaks but it was a great start.  Thank you.  Will be included in the next update.

**Comment by njcyx** [comment]
Thanks. I did some tests and this value seems to be the goods value, not declared value. I adjusted this value several times and no changes for the shipping quote.
