### ISSUE TITLE
Fix Intl priority quote

### ISSUE THREAD

**Issue by njcyx** [scottcwilson/zencart_fedexrest#2]
Change line 169 from the following

` $this->types['INTERNATIONAL_PRIORITY'] = array('icon' => '', 'handling_fee' => MODULE_SHIPPING_FEDEX_REST_INT_EXPRESS_HANDLING_FEE);`

To
`$this->types['FEDEX_INTERNATIONAL_PRIORITY'] = array('icon' => '', 'handling_fee' => MODULE_SHIPPING_FEDEX_REST_INT_EXPRESS_HANDLING_FEE);`

The correct servicetype for priority is FEDEX_INTERNATIONAL_PRIORITY

**Comment by scottcwilson** [comment]
You are correct - table is here: https://developer.fedex.com/api/en-mx/guides/api-reference.html#servicetypes

It's awesome how some of these start with FEDEX_ and others don't. :(

**Comment by scottcwilson** [comment]
This fix will be in the next release, coming this week.  Thank you.

**Comment by njcyx** [comment]
This name mismatch issue happened before with the previous plug-in, when changed from RateService_v20.wsdl to RateService_v31.wsdl.
