### ISSUE TITLE
Display Intl Connect Plus

### ISSUE THREAD

**Issue by njcyx** [scottcwilson/zencart_fedexrest#3]
Not sure if anyone use it other than me. 

Add the following code near line 174
`         if (MODULE_SHIPPING_FEDEX_REST_INTERNATIONAL_CONNECT_PLUS == 'true') {
            $this->types['FEDEX_INTERNATIONAL_CONNECT_PLUS'] = array('icon' => '', 'handling_fee' => MODULE_SHIPPING_FEDEX_REST_INT_EXPRESS_HANDLING_FEE);
         }`

Add the following code near line 562
`         $db->Execute("insert into " . TABLE_CONFIGURATION . " (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, set_function, date_added) values ('Enable Intl Connect Plus', 'MODULE_SHIPPING_FEDEX_REST_INTERNATIONAL_CONNECT_PLUS', 'true', 'Enable Intl Connect Plus', '6', '56', 'zen_cfg_select_option(array(\'true\', \'false\'), ', now())");`

Add the following code near line 613
 'MODULE_SHIPPING_FEDEX_REST_INTERNATIONAL_CONNECT_PLUS',

**Comment by scottcwilson** [comment]
OK this will be in the next release.
