### ISSUE TITLE
Cannot differentiate Saturday delivery (e.g. Priority overnight vs priority overnight saturday delivery)

### ISSUE THREAD

**Issue by njcyx** [scottcwilson/zencart_fedexrest#6]
As reported here. 

https://www.zen-cart.com/showthread.php?229562-FedEx-Shipping-using-REST-API&p=1399775#post1399775

**Comment by njcyx** [comment]
I referred to the previous legacy fedex plug-in. Here is my "band-aid" solution:

1. Add the following section at first, to give a parameter for Saturday delivery.
                  $saturday = false;
               if (!empty($rate['commit']['saturdayDelivery']) && $rate['commit']['saturdayDelivery'] == 1) {
                  $transitTime .= MODULE_SHIPPING_FEDEXREST_SATURDAY; 
                  $saturday = true;
               }
2. Near original line 515-519, change the following code

               $methods[] = [
                  'id' => str_replace('_', '', $serviceType),
                  'title' => ucwords(strtolower(str_replace('_', ' ', $serviceType))) . $transitTime,
                  'cost' => $cost
               ];

To

               if ($saturday)
               {
               $methods[] = [
                  'id' => str_replace('_', '', $serviceType) . "SATURDAY",
                 'title' => ucwords(strtolower(str_replace('_', ' ', $serviceType))) . $transitTime,
                  'cost' => $cost
               ];
            }
            else {

               $methods[] = [
                  'id' => str_replace('_', '', $serviceType),
                  'title' => ucwords(strtolower(str_replace('_', ' ', $serviceType))) . $transitTime,
                  'cost' => $cost
               ];
            }

I prefer to use selection command ($a?$b:$c) but I don't know why it didn't work...

**Comment by scottcwilson** [comment]
Were you able to get a response containing `$rate['commit']['saturdayDelivery'] ` ?   I just wasn't, that's why I haven't moved forward.    I think the challenge is you have a very small window where you can run this test.

**Comment by proseLA** [comment]
>  I think the challenge is you have a very small window where you can run this test.

i thought i previously covered this.  the window for testing is WIDE open.  one only needs to change the ship date to get saturday delivery options.

i think this line can be modified to use a ship date that would provide saturday deliveries.

https://github.com/scottcwilson/zencart_fedexrest/blob/f3c7a4e68b1930109cbcb59ed7a41fc566650a89/includes/modules/shipping/fedexrest.php#L411

**Comment by scottcwilson** [comment]
Right.  Please let me know what value of `shipDateStamp` you can use that will give `$rate['commit']['saturdayDelivery'] = 1` in the response.  Please test so you're sure it actually works.  Because I spent an hour fiddling with it and couldn't make it work.

**Comment by proseLA** [comment]
i'll put it on my list!

**Comment by njcyx** [comment]
> `shipDateStamp`

I'm not sure what info you need...I can email you the response log file if you like?

I just did a test to ship a package this Friday (4/5/2024). I cannot find "shipDateStamp" in the response log file...But I can find some info such as the following:

                                    [deliveryDate] => 2024-04-06T12:00:00
                                    [deliveryDay] => SAT
                                    [commitDate] => 2024-04-06T12:00:00
                                    [commitDays] => Array

Or

                            [serviceType] => PRIORITY_OVERNIGHT
                            [serviceName] => FedEx Priority Overnight®
                            [packagingType] => YOUR_PACKAGING
                            [commit] => Array
                                (
                                    [dateDetail] => Array
                                        (
                                            [dayOfWeek] => Sat
                                            [dayFormat] => 2024-04-06T12:00:00
                                        )

                                    [derivedOriginDetail] => Array {}

                                    [derivedDestinationDetail] => Array {}

                                    [saturdayDelivery] => 1
                                )


Here is the regular one

                            [serviceType] => PRIORITY_OVERNIGHT
                            [serviceName] => FedEx Priority Overnight®
                            [packagingType] => YOUR_PACKAGING
                            [commit] => Array
                                (
                                    [dateDetail] => Array
                                        (
                                            [dayOfWeek] => Mon
                                            [dayFormat] => 2024-04-08T12:00:00                                       
                                        )

After I changed the ship date, I can test Saturday delivery options today. Yes, I can find "[saturdayDelivery] => 1" in the response data.

**Comment by scottcwilson** [comment]
You're testing today (Monday) and getting Saturday for the priority overnight delivery date?

**Comment by njcyx** [comment]
> You're testing today (Monday) and getting Saturday for the priority overnight delivery date?

No, I'm testing if send out a package this Friday.

Sorry, I have edited my response several times. It looks like you are online. Please refresh the page...

**Comment by njcyx** [comment]
So to send the package out on Thursday, I should have Fedex 2day saturday delivery option.

To send the package out on Friday, I should have priority and first overnight with satruday delivery options. 

No Sat delivery options during Mon-Wed, Sat-Sun.

**Comment by scottcwilson** [comment]
Did you run this test on Thursday/Friday?  Or did you change the code so you could test today?  Please let me know EXACTLY what you are doing so I don't have to guess.

**Comment by proseLA** [comment]
> So to send the package out on Thursday, I should have Fedex 2day saturday delivery option.
> 
> To send the package out on Friday, I should have priority and first overnight with satruday delivery options.
> 
> No Sat delivery options during Mon-Wed, Sat-Sun.

i believe that is correct....

**Comment by njcyx** [comment]
> Did you run this test on Thursday/Friday? Or did you change the code so you could test today? Please let me know EXACTLY what you are doing so I don't have to guess.

Yesterday (Monday), I changed the code to ship the package this Friday, so I can get the shipping quote for Saturday delivery. 

I cannot get any Saturday delivery quote if the shipping date is between Mon to Wed. 

Sorry for the confusion.

**Comment by scottcwilson** [comment]
> Yesterday (Monday), I changed the code to ship the package this Friday, so I can get the shipping quote for Saturday delivery.

I'm begging you.  PLEASE TELL ME EXACTLY WHAT YOU DID SO I CAN REPRODUCE IT.

**Comment by njcyx** [comment]
I don't get your question.

Do you want to know how I modify the code to temp fix this issue?

Or do you want me to show you how to get the shipping quote for saturday delivery?

**Comment by njcyx** [comment]
Again, I can email you the copies of request and response log files. You can find all the data regarding this shipment there.

**Comment by scottcwilson** [comment]
You said, "I changed the code to ship the package this Friday ..."

What did you change, exactly.  Diff the original file and your file so I can see the code change.

**Comment by njcyx** [comment]
LOL...Sorry, we are not on the same page.

Give me a second. I will let you know my code.

**Comment by njcyx** [comment]
In your code before line 384 ($rate_data = [), I added the following code:

         $shipDate = new DateTime(); 
         $now = mktime(date("G"), date("i"), 0, 0, 0, 0);
         $cutoff_time = mktime(16, 00, 0, 0, 0, 0); // Based on server timezone. 16 is 4pm ET.
         if ($now >= $cutoff_time) {
            $shipDate->modify('+4 day');
         } 

Then near your line 411, change the following code from 

 "shipDateStamp" => date("Y-m-d"),

To

'shipDateStamp' => $shipDate->format('Y-m-d'),   //EOF

I used the code above for 1) set cutoff time 2) easily change shipping date.  Yesterday (Monday), I added "4" to the shipping date.

**Comment by njcyx** [comment]
Sorry, my last post seems confused me.

Add the following code before $rate_data = [] line:

$shipDate = new DateTime(); 
$shipDate->modify('next friday'); 

Then near shipDateStamp line, change to the following:

'shipDateStamp' => $shipDate->format('Y-m-d'),

**Comment by scottcwilson** [comment]
OK thank you.  That's what I was hoping for.

I have a ton of release related work to do right now, I'll get back to this as soon as I can.

**Comment by njcyx** [comment]
> Sorry, my last post seems confused me.
> 
> Add the following code before $rate_data = [] line:
> 
> $shipDate = new DateTime(); $shipDate->modify('next friday');
> 
> Then near shipDateStamp line, change to the following:
> 
> 'shipDateStamp' => $shipDate->format('Y-m-d'),

I just tried my 3 line code again and it worked. Saturday delivery shown up properly. You should be able to reproduce my result as well.

Sure. Take time. It is not urgent.

**Comment by scottcwilson** [comment]
To get the `commit` element in the response, you have to set `Show Estimated Transit Time` in the module's config to True.  This was why I wasn't seeing it. 

Set this config and you'll see the code works fine without changes (of course if you are not testing Thursday or Friday you'll have to change the shipDate).

<img width="400" alt="ship" src="https://github.com/scottcwilson/zencart_fedexrest/assets/4391638/676890e4-46a7-47f8-ab22-201b9e98bd57">

**Comment by njcyx** [comment]
Thanks for your time and efforts

But when you get a chance, please re-read my original post regarding this issue. My issue is not related to whether Saturday delivery quote is display properly or not, **but the sub-total value and selected shipping method is incorrect when you select between regular shipping or saturday delivery shipping.**

The root cause is due to 'id' element under $methods[] is not differentiated between non-Saturday and saturday delivery shipping methods. 

Yes, my "Show Estimated Transit Time" is set to true. There will be no Saturday quote if this parameter is set to false.

**Comment by scottcwilson** [comment]
OK, so if you ship Thursday, and you have two day AND Saturday delivery (and show estimated transit time) ON, it can't tell the difference between 2 day (arriving Monday) and 2 day (arriving Saturday).  This should be fixed, please pull from Github.

**Comment by njcyx** [comment]
Hi Scott, I just tested your latest 1.3.1 code and it solved this issue. Your code looks much better than my solution. Thanks for your time and contribution.

**Comment by scottcwilson** [comment]
Honestly I'm not positive - yours was shorter.  You seemed to suggest your change was a hack, so I didn't carefully consider it before debugging the problem myself (after I figured out the required configuration to even see the issue).  Anyhow, all's well that ends well.

**Comment by njcyx** [comment]
Actually, I'm not a "professional" developer and I can only do some "band-aid" stuffs with some luck lol...I can barely understand the new section near $method_ok in your fix but I'm pretty sure there must be a reason. It is highly possible that I missed some conditions in my hack.

I tested this updated code several times and it worked fine, so it should be good for production. 

Thanks again.
