### ISSUE TITLE
versioning and tags...

### ISSUE THREAD

**Issue by proseLA** [scottcwilson/zencart_fedexrest#8]
scott,
i would potentially like to work on this module as i am now in the process of implementing it on a clients site.

given that you know how to do releases on github, can we create those releases and tags here?  i find it very helpful to know where we are on the repo in relationship to a tag.  i do it for my auth.net module.

as a minor side note, you have a define wrong, it states:
```
You will need to have registered an account with FedEx to use this module. Please see the README.TXT file.
```
i have not found a README.TXT file.  there is a README.md file.

finally, i thought [your instructions](https://github.com/scottcwilson/zencart_fedexrest/wiki/Installation-Instructions) were quite good.  i only missed the part of the production key.  i think having a sandbox key is VERY important, especially for those of us that have integrated fedex shipping into the back end of zen-cart, and would like to play around with other things that the API offers.

**Comment by scottcwilson** [comment]
It worked out well that you posted this because I completely fat-fingered the build.  OK starting with 1.3.1, the releases are now numbered and tagged. 

Maybe this should be a recommended standard for Github based releases in the plugins library.  It has a lot to recommend it.

**Comment by proseLA** [comment]
getting rid of the Rest API in description is MUCH better.

**Comment by scottcwilson** [comment]
It's about time.  If you are still running the old one and want a side by side comparison, change the name of the old one! :)
