### ISSUE TITLE
Hey Scott - Attempt to read property "delivery" on null

### ISSUE THREAD

**Issue by JeffMash** [scottcwilson/zencart_fedexrest#9]
I am testing this on a ZC 1.5.8.a running PHP 8.3 and OPC plugin 2.4.6.

I  am getting this error in the logs even though the plugin seems to be displaying prices just fine:

--> PHP Warning: Attempt to read property "delivery" on null in /home/domain/public_html/store/includes/modules/shipping/fedexrest.php on line 123.

--> PHP Warning: Trying to access array offset on value of type null in /home/domain/public_html/store/includes/modules/shipping/fedexrest.php on line 123.

**Comment by scottcwilson** [comment]
Fixed in the latest update. Get it here or from the plugins library.
